// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEliDzgx = "eli_dzgx"

// EliDzgx mapped from table <eli_dzgx>
type EliDzgx struct {
	ID   int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name" json:"name"`
	Gxxy string `gorm:"column:gxxy;comment:关系像意" json:"gxxy"` // 关系像意
	Dz   string `gorm:"column:dz" json:"dz"`
	Xy   string `gorm:"column:xy;comment:象意" json:"xy"` // 象意
	Hhxg string `gorm:"column:hhxg" json:"hhxg"`
}

// TableName EliDzgx's table name
func (*EliDzgx) TableName() string {
	return TableNameEliDzgx
}
