// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEliSwxy = "eli_swxy"

// EliSwxy mapped from table <eli_swxy>
type EliSwxy struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	R1           string `gorm:"column:r1" json:"r1"`
	R2           string `gorm:"column:r2" json:"r2"`
	Relationship string `gorm:"column:relationship;comment:生 克 同" json:"relationship"` // 生 克 同
	Des          string `gorm:"column:des" json:"des"`
	Type         string `gorm:"column:type" json:"type"`
}

// TableName EliSwxy's table name
func (*EliSwxy) TableName() string {
	return TableNameEliSwxy
}
