// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEliAgent = "eli_agent"

// EliAgent mapped from table <eli_agent>
type EliAgent struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string    `gorm:"column:name" json:"name"`
	Code     string    `gorm:"column:code" json:"code"`
	CreateAt time.Time `gorm:"column:create_at" json:"create_at"`
}

// TableName EliAgent's table name
func (*EliAgent) TableName() string {
	return TableNameEliAgent
}
