// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEliSwwx = "eli_swwx"

// EliSwwx mapped from table <eli_swwx>
type EliSwwx struct {
	ID               int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Wuxing           string `gorm:"column:wuxing" json:"wuxing"`
	Num              int32  `gorm:"column:num" json:"num"`
	AssessingMatters string `gorm:"column:assessing_matters" json:"assessing_matters"`
	Health           string `gorm:"column:health" json:"health"`
}

// TableName EliSwwx's table name
func (*EliSwwx) TableName() string {
	return TableNameEliSwwx
}
