// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpwCharBackground = "spw_char_background"

// SpwCharBackground mapped from table <spw_char_background>
type SpwCharBackground struct {
	ID      int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CharID  int64     `gorm:"column:char_id" json:"char_id"`
	Code    string    `gorm:"column:code" json:"code"`
	Lan     string    `gorm:"column:lan" json:"lan"`
	Role    string    `gorm:"column:role" json:"role"`
	Prompt  string    `gorm:"column:prompt" json:"prompt"`
	Seq     int32     `gorm:"column:seq" json:"seq"`
	AddTime time.Time `gorm:"column:add_time" json:"add_time"`
	Flag    int32     `gorm:"column:flag;not null" json:"flag"`
	Answer  string    `gorm:"column:answer" json:"answer"`
}

// TableName SpwCharBackground's table name
func (*SpwCharBackground) TableName() string {
	return TableNameSpwCharBackground
}
