// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpwSampleChat = "spw_sample_chat"

// SpwSampleChat mapped from table <spw_sample_chat>
type SpwSampleChat struct {
	ID      int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CharID  int64     `gorm:"column:char_id" json:"char_id"`
	Code    string    `gorm:"column:code" json:"code"`
	Lan     string    `gorm:"column:lan" json:"lan"`
	Samq    string    `gorm:"column:samq" json:"samq"`
	Sama    string    `gorm:"column:sama" json:"sama"`
	AddTime time.Time `gorm:"column:add_time" json:"add_time"`
	Flag    int32     `gorm:"column:flag" json:"flag"`
}

// TableName SpwSampleChat's table name
func (*SpwSampleChat) TableName() string {
	return TableNameSpwSampleChat
}
