// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpwMethod = "spw_method"

// SpwMethod mapped from table <spw_method>
type SpwMethod struct {
	ID   int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Lan  string `gorm:"column:lan" json:"lan"`
	Code string `gorm:"column:code" json:"code"`
	Name string `gorm:"column:name" json:"name"`
	Flag int32  `gorm:"column:flag;not null" json:"flag"`
}

// TableName SpwMethod's table name
func (*SpwMethod) TableName() string {
	return TableNameSpwMethod
}
