// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpwMysart = "spw_mysart"

// SpwMysart mapped from table <spw_mysart>
type SpwMysart struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code  string `gorm:"column:code" json:"code"`
	Lan   string `gorm:"column:lan" json:"lan"`
	Flag  int32  `gorm:"column:flag" json:"flag"`
	Name  string `gorm:"column:name" json:"name"`
	Brief string `gorm:"column:brief" json:"brief"`
}

// TableName SpwMysart's table name
func (*SpwMysart) TableName() string {
	return TableNameSpwMysart
}
