// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSpwCharacter = "spw_character"

// SpwCharacter mapped from table <spw_character>
type SpwCharacter struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CharName     string `gorm:"column:char_name" json:"char_name"`
	CharAvatar   string `gorm:"column:char_avatar" json:"char_avatar"`
	CharInfo     string `gorm:"column:char_info" json:"char_info"`
	CharBirth    string `gorm:"column:char_birth" json:"char_birth"`
	CharAge      string `gorm:"column:char_age" json:"char_age"`
	CharGender   string `gorm:"column:char_gender" json:"char_gender"`
	CharPlace    string `gorm:"column:char_place" json:"char_place"`
	Lan          string `gorm:"column:lan" json:"lan"`
	Code         string `gorm:"column:code" json:"code"`
	Flag         int32  `gorm:"column:flag;not null" json:"flag"`
	CharFullBody string `gorm:"column:char_full_body" json:"char_full_body"`
	CharProfile  string `gorm:"column:char_profile" json:"char_profile"`
	CharNature   int32  `gorm:"column:char_nature" json:"char_nature"`
	CharRegion   string `gorm:"column:char_region" json:"char_region"`
	ModelName    string `gorm:"column:model_name" json:"model_name"`
	ModelKey     string `gorm:"column:model_key" json:"model_key"`
}

// TableName SpwCharacter's table name
func (*SpwCharacter) TableName() string {
	return TableNameSpwCharacter
}
