// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysCatalog = "sys_catalog"

// SysCatalog mapped from table <sys_catalog>
type SysCatalog struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NameCn   string `gorm:"column:name_cn" json:"name_cn"`
	NameCode string `gorm:"column:name_code" json:"name_code"`
	Flag 	 int 	`gorm:"column:flag" json:"flag"`
}

// TableName SysCatalog's table name
func (*SysCatalog) TableName() string {
	return TableNameSysCatalog
}

type SysPreQuestion struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Content   string `gorm:"column:content" json:"content"`
	Desc string `gorm:"column:desc" json:"desc"`
	CatId string `gorm:"column:cat_id" json:"cat_id"`
	Flag 	 int 	`gorm:"column:flag" json:"flag"`
}

func (*SysPreQuestion) TableName() string {
	return "sys_pre_question"
}

type SysCatStruct struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CatId string `gorm:"column:cat_id" json:"cat_id"`
	Cntstruct string `gorm:"column:cntstruct" json:"cntstruct"`
	Seq int `gorm:"column:seq" json:"seq"`
	Flag int `gorm:"column:flag" json:"flag"`
}

func (*SysCatStruct) TableName() string {
	return "sys_cat_struct"
}

type SysBgmeans struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Key string `gorm:"column:key" json:"key"`
	Meaning string `gorm:"column:meaning" json:"meaning"`
	Type int `gorm:"column:type" json:"type"`
	Flag int `gorm:"column:flag" json:"flag"`
}

func (*SysBgmeans) TableName() string {
	return "sys_bgmeaning"
}