// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysCatalog = "sys_catalog"

// SysCatalog mapped from table <sys_catalog>
type SysCatalog struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	NameCn   string `gorm:"column:name_cn" json:"name_cn"`
	NameCode string `gorm:"column:name_code" json:"name_code"`
}

// TableName SysCatalog's table name
func (*SysCatalog) TableName() string {
	return TableNameSysCatalog
}
