http: 
  port: 8088
mysql: 
  port: 3306
  host: 123.249.126.212
  username: root
  password: SDFD12312dddasdas1#@123123
  db: spirit_war
log:
  level: info
aes:
  keyPath: ./pk/vega_aes_32_3957c3855880.key
chains: 
  Ethereum: https://mainnet.infura.io/v3/3a487e3317dd401caff0ec9033079989
  BSC: https://bsc-dataseed4.ninicoin.io
google: 
  clientId: 890462275164-cutk7ea593vqqv5i12rq0q4gsbnufed1.apps.googleusercontent.com
openai:
  apikey: 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
env:
  log: /log
  en_i818: locales/en.json
  zh_cn_i818: locales/zh_cn.json