// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEliSwfl = "eli_swfl"

// EliSwfl mapped from table <eli_swfl>
type EliSwfl struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Renyuan   string `gorm:"column:renyuan" json:"renyuan"`
	Guishen   string `gorm:"column:guishen" json:"guishen"`
	Shenjiang string `gorm:"column:shenjiang" json:"shenjiang"`
	Difen     string `gorm:"column:difen" json:"difen"`
	Type      string `gorm:"column:type" json:"type"`
}

// TableName EliSwfl's table name
func (*EliSwfl) TableName() string {
	return TableNameEliSwfl
}
